version: "3.7"

services:
    postgres:
      image: postgres:17
      ports:
        - "5432:5432"
      environment:
        POSTGRES_DB: "tasks"
        POSTGRES_USER: "admin"
        POSTGRES_PASSWORD: "passw0rd"
